---
- hosts: test-servers
  become: true
  tasks:
  - name: update apt
    command: apt-get update

  - name: install docker
    command: apt install -y docker.io

  - name: start docker service
    command: systemctl start docker

  - name: deploy application
    command: docker run -itd -p 8081:8081 elexad/capstone-srpingboot:1
